tomcat_version: "9.0.73"
tomcat_user: tomcat
tomcat_group: tomcat
tomcat_install_dir: "/opt"

tomcat_install_java: true
java_package: "openjdk-17-jdk"
java_home: ""

clean_tomcat_downloaded: false
force_tomcat_install: false

tomcat_manager:
  host_manager_allow: ".*"
  manager_allow: ".*"
  roles:
  - rolename: "manager-gui"
  users:
  - username: "tomcat"
    password: "tomcat"
    roles: "manager-gui"

server:
  host: "localhost"
  address: "0.0.0.0"
  port: 8080
  timeout: 20000
  max_post_size: 209715200
  redirect_port: 8443
  auto_deployment: true 

set_env:
 - 'JAVA_OPTS="-Xms512M -Xmx512M"'
